"""
Large Language Model (LLM) Utilities Module.

This module defines the core interfaces and concrete implementations for interacting with various
LLM providers such as OpenRouter and OpenAI. It employs the Strategy and Factory design patterns 
to ensure a consistent interface across different services (adhering to SOLID principles).

It includes a base class (`LLMProvider`) to define the contract, specific implementations for 
different providers, and a `ToolRegistry` class to manage and execute tools (functions) that 
the LLMs can call as part of the 'Tool Use' and 'ReAct' design patterns.

Overall, it handles text generation, coordinates tool calling capabilities, and abstracts away
the complexities of direct API interaction.
"""

from abc import ABC, abstractmethod
from typing import List, Dict, Any, Callable, Optional
from utils import get_api_key, get_model_configuration, get_parameter_configuration
import json


class LLMProvider(ABC):
    """
    Abstract Base Class representing a generic LLM Provider.
    
    This class enforces a standard interface for any language model provider (e.g., OpenAI, Anthropic, 
    OpenRouter) integrated into the Agentic RAG system.
    """

    @abstractmethod
    def generate(self, messages: List[Dict[str, Any]], model: str, **kwargs) -> str:
        """
        Generates a standard text response from the language model based on the provided messages.

        Args:
            messages (List[Dict[str, Any]]): The conversation history formatted as a list of dictionaries 
                                             (e.g., [{"role": "user", "content": "Hello"}]).
            model (str): The specific model identifier to be used (e.g., "gpt-4").
            **kwargs: Additional parameters such as temperature, max_tokens, etc.

        Returns:
            str: The generated text response from the language model.
        """
        pass

    @abstractmethod
    def generate_with_tools(self, messages: List[Dict[str, Any]], model: str, tools: List[Dict[str, Any]], **kwargs) -> Any:
        """
        Generates a response from the language model, giving it the ability to invoke external tools.

        Args:
            messages (List[Dict[str, Any]]): The conversation history.
            model (str): The specific model identifier to be used.
            tools (List[Dict[str, Any]]): A list of tool definitions (usually JSON schema) describing 
                                          what functions the model can call.
            **kwargs: Additional parameters such as temperature, tool_choice, etc.

        Returns:
            Any: The response from the model, which could be a standard text message or a structured 
                 tool call request.
        """
        pass


class OpenAIProvider(LLMProvider):
    """
    Concrete implementation of the LLMProvider for OpenAI's API.
    
    This class handles the specific formatting, API calls, and response parsing required to interact 
    with OpenAI models (like gpt-4 or gpt-3.5-turbo).
    """
    
    def __init__(self, api_key: str):
        """
        Initializes the OpenAI provider with the required API key.

        Args:
            api_key (str): The valid API key for authenticating with OpenAI services.
        """
        self.api_key = api_key
        # Typically, we would initialize the official openai python client here:
        # import openai
        # self.client = openai.OpenAI(api_key=self.api_key)

    def generate(self, messages: List[Dict[str, Any]], model: str, **kwargs) -> str:
        """
        Calls the OpenAI API to generate a standard text completion.

        Args:
            messages (List[Dict[str, Any]]): The conversation history.
            model (str): The model to use (e.g., 'gpt-4o').
            **kwargs: Optional generation arguments (temperature, max_tokens).

        Returns:
            str: The plain text content generated by the assistant.
        """
        from openai import OpenAI
        client = OpenAI(api_key=self.api_key, timeout=120.0)
        response = client.chat.completions.create(
            model=model,
            messages=messages,
            **kwargs
        )
        return response.choices[0].message.content

    def generate_with_tools(self, messages: List[Dict[str, Any]], model: str, tools: List[Dict[str, Any]], **kwargs) -> Any:
        """
        Calls the OpenAI API, providing it with definitions of tools it can use.

        Args:
            messages (List[Dict[str, Any]]): The conversation history.
            model (str): The model to use.
            tools (List[Dict[str, Any]]): The JSON schema representations of the available tools.
            **kwargs: Optional generation arguments.

        Returns:
            Any: The raw message object from OpenAI, which may include a 'tool_calls' attribute
                 if the model decided to invoke a tool.
        """
        from openai import OpenAI
        client = OpenAI(api_key=self.api_key, timeout=120.0)
        response = client.chat.completions.create(
            model=model,
            messages=messages,
            tools=tools,
            **kwargs
        )
        return response.choices[0].message


class OpenRouterProvider(LLMProvider):
    """
    Concrete implementation of the LLMProvider for the OpenRouter API.
    
    OpenRouter acts as a unified interface to multiple models (including Anthropic, Meta, etc.).
    This class handles the specific headers (like HTTP-Referer) and endpoint logic for OpenRouter.
    """
    
    def __init__(self, api_key: str):
        """
        Initializes the OpenRouter provider with the required API key.

        Args:
            api_key (str): The valid API key for authenticating with OpenRouter services.
        """
        self.api_key = api_key

    def generate(self, messages: List[Dict[str, Any]], model: str, **kwargs) -> str:
        """
        Calls the OpenRouter API to generate a standard text completion.

        Args:
            messages (List[Dict[str, Any]]): The conversation history.
            model (str): The model identifier specific to OpenRouter (e.g., 'anthropic/claude-3-opus').
            **kwargs: Optional generation arguments.

        Returns:
            str: The plain text content generated by the routed model.
        """
        from openai import OpenAI
        client = OpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key=self.api_key,
            timeout=120.0
        )
        response = client.chat.completions.create(
            model=model,
            messages=messages,
            **kwargs
        )
        return response.choices[0].message.content

    def generate_with_tools(self, messages: List[Dict[str, Any]], model: str, tools: List[Dict[str, Any]], **kwargs) -> Any:
        """
        Calls the OpenRouter API, providing it with tool definitions.

        Args:
            messages (List[Dict[str, Any]]): The conversation history.
            model (str): The OpenRouter model identifier.
            tools (List[Dict[str, Any]]): The JSON schema representations of the available tools.
            **kwargs: Optional generation arguments.

        Returns:
            Any: The response object potentially containing tool calls.
        """
        from openai import OpenAI
        client = OpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key=self.api_key,
            timeout=120.0
        )
        response = client.chat.completions.create(
            model=model,
            messages=messages,
            tools=tools,
            **kwargs
        )
        return response.choices[0].message


class DummyLocalProvider(LLMProvider):
    """
    A dummy implementation of LLMProvider for testing purposes when "dummy" is specified in the model name.
    """
    def generate(self, messages: List[Dict[str, Any]], model: str, **kwargs) -> str:
        return "This is a placeholder response from DummyLocalProvider."

    def generate_with_tools(self, messages: List[Dict[str, Any]], model: str, tools: List[Dict[str, Any]], **kwargs) -> Any:
        return {"role": "assistant", "content": None, "tool_calls": []}


class ToolRegistry:
    """
    A registry to manage, store, and execute tools (functions) available to the AI agents.
    
    This class maps string names of tools (as requested by the LLM) to actual Python callable functions.
    It facilitates the execution phase of the 'Tool Use' and 'ReAct' design patterns.
    """
    
    def __init__(self):
        """
        Initializes an empty registry.
        
        Args:
            None
        """
        # The internal dictionary mapping tool names to their corresponding Python functions
        self._registered_tools: Dict[str, Callable] = {}

    def register_tool(self, tool_name: str, tool_function: Callable) -> None:
        """
        Registers a new tool in the registry, making it available for execution.

        Args:
            tool_name (str): The unique string identifier for the tool (should match the name in the JSON schema).
            tool_function (Callable): The actual Python function to execute when the tool is called.

        Returns:
            None
        """
        self._registered_tools[tool_name] = tool_function
        print(f"DEBUG: Successfully registered tool '{tool_name}'")

    def execute_tool(self, tool_name: str, tool_arguments: Dict[str, Any]) -> Any:
        """
        Executes a registered tool using the arguments provided by the LLM.

        Args:
            tool_name (str): The name of the tool to execute.
            tool_arguments (Dict[str, Any]): A dictionary of arguments parsed from the LLM's tool call request.

        Returns:
            Any: The result of the executed function. Typically converted to a string or JSON later.
            
        Raises:
            ValueError: If the requested tool_name is not found in the registry.
        """
        if tool_name not in self._registered_tools:
            raise ValueError(f"Tool '{tool_name}' is not registered in the ToolRegistry.")
            
        target_function = self._registered_tools[tool_name]
        
        # Execute the function by unpacking the arguments dictionary
        try:
            execution_result = target_function(**tool_arguments)
            return execution_result
        except Exception as execution_error:
            return f"Error executing tool {tool_name}: {str(execution_error)}"

    def get_available_tools(self) -> List[str]:
        """
        Retrieves a list of the names of all currently registered tools.

        Args:
            None

        Returns:
            List[str]: A list containing the string identifiers of all available tools.
        """
        return list(self._registered_tools.keys())


def create_llm_provider(config: Optional[Dict] = None) -> LLMProvider:
    if config is None:
        config = get_parameter_configuration()
        
    model = config.get("model", "gpt-4o-mini")
    provider_config = config.get("provider") or {}
    provider = provider_config.get("default", "openrouter") if isinstance(provider_config, dict) else "openrouter"

    if "dummy" in (model or "").lower():
        return DummyLocalProvider()

    if provider == "openai":
        return OpenAIProvider(api_key=get_api_key("OPENAI"))
    elif provider == "openrouter":
        return OpenRouterProvider(api_key=get_api_key("OPENROUTER"))
    else:
        # fallback
        return OpenAIProvider(api_key=get_api_key("OPENAI"))


import time

class LLM:
    """
    A high-level wrapper around LLMProvider that provides a simple generate interface
    for notebooks and applications, returning responses along with token counts and latency.
    """
    def __init__(self, provider: Optional[LLMProvider] = None, model: Optional[str] = None):
        self.config = get_parameter_configuration()
        self.provider = provider or create_llm_provider(self.config)
        self.model = model or self.config.get("model", "gpt-4o-mini")

    def generate(self, prompt: str, system_prompt: Optional[str] = None, **kwargs) -> Dict[str, Any]:
        """
        Generates a response from the underlying provider and computes stats.
        """
        messages = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt})

        start_time = time.time()
        response_text = self.provider.generate(messages=messages, model=self.model, **kwargs)
        latency_ms = int((time.time() - start_time) * 1000)

        # Estimate tokens
        try:
            from utils.token_utils import count_tokens_in_messages, count_tokens_in_text
            total_tokens = count_tokens_in_messages(messages, self.model) + count_tokens_in_text(response_text, self.model)
        except ImportError:
            total_tokens = 0

        return {
            "response": response_text,
            "total_tokens": total_tokens,
            "latency_ms": latency_ms
        }
